# Application Name
spring.application.name=demo

# Server Port
server.port=8080

# Connection details from your MySQL Workbench
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/paymyfee
spring.datasource.username=root
spring.datasource.password=Tarak@2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true